import { existsSync, writeFileSync } from 'fs'
import { join } from 'path'

const FILENAME = 'compose.yaml'

const TEMPLATE = `
# Generated by compose-gen
# Docker Compose specification: https://docs.docker.com/compose/compose-file/
name: my-project
`

export function initCommand() {
  const targetPath = join(process.cwd(), FILENAME)

  if (existsSync(targetPath)) {
    console.error(`❌  ${FILENAME} already exists in this directory.`)
    process.exit(1)
  }

  writeFileSync(targetPath, TEMPLATE, 'utf-8')
  console.log(`✅  ${FILENAME} created successfully.`)
}